services:
  linx-xiling:
    image: linx-xiling:1.1.0
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app/data
      - ./output:/app/output
      - ./config:/app/config:ro

    entrypoint: ["python3", "/app/linx-xiling.py"]
